services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: sense_by_spotify
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
